import { GalleryView } from '@/components/gallery-view'
import { loadHtmlFiles } from '@/lib/load-html-files'

export default async function Home() {
    const htmlFiles = await loadHtmlFiles()

    return (
        <div className="container mx-auto px-4 py-8">
            <div className="mb-8">
                <h1 className="text-4xl font-bold text-foreground mb-4">
                    LLM HTML Gallery
                </h1>
                <p className="text-lg text-muted-foreground">
                    A curated collection of HTML content generated by Large Language Models
                </p>
            </div>

            <GalleryView htmlFiles={htmlFiles} />
        </div>
    )
}
