'use client';

import { useEffect, useState } from 'react';
import { GalleryView } from '@/components/gallery-view';
import { FastGalleryMode } from '@/components/fast-gallery-mode';
import { fetchGenerations } from '@/lib/gallery-adapter';

export default function Home() {
    const [htmlFiles, setHtmlFiles] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [isAdminMode, setIsAdminMode] = useState(false);

    useEffect(() => {
        // Load HTML files from API
        const loadFiles = async () => {
            try {
                const response = await fetch('/api/html-files');
                if (!response.ok) {
                    throw new Error('Failed to fetch HTML files');
                }
                const files = await response.json();
                setHtmlFiles(files);
            } catch (error) {
                console.error('Failed to load HTML files:', error);
            } finally {
                setLoading(false);
            }
        };

        loadFiles();

        // Check if admin mode is enabled in localStorage
        const adminMode = localStorage.getItem('llm-gallery-admin-mode') === 'true';
        setIsAdminMode(adminMode);
    }, []);

    const handleItemClick = (item: any) => {
        // Handle item click - could open a modal or navigate to detail page
        console.log('Item clicked:', item);
    };

    if (loading) {
        return (
            <div className="container mx-auto px-4 py-8">
                <div className="flex items-center justify-center h-64">
                    <div className="text-lg text-muted-foreground">Loading...</div>
                </div>
            </div>
        );
    }

    // Show admin mode (current gallery view) only if admin mode is enabled
    if (isAdminMode) {
        return (
            <div className="container mx-auto px-4 py-8">
                <div className="mb-8">
                    <h1 className="text-4xl font-bold text-foreground mb-4">
                        LLM HTML Gallery - Admin Mode
                    </h1>
                    <p className="text-lg text-muted-foreground">
                        A curated collection of HTML content generated by Large Language Models
                    </p>
                </div>

                <GalleryView htmlFiles={htmlFiles} />
            </div>
        );
    }

    // Default: Show Fast Gallery Mode for all users
    return (
        <div>
            <div className="container mx-auto px-4 py-6">
                <div className="mb-6">
                    <h1 className="text-4xl font-bold text-foreground mb-4">
                        LLM HTML Gallery
                    </h1>
                    <p className="text-lg text-muted-foreground">
                        A curated collection of HTML content generated by Large Language Models
                    </p>
                </div>
            </div>
            
            <FastGalleryMode 
                fetchGenerations={(page, filters) => fetchGenerations(htmlFiles, page, filters)}
                onItemClick={handleItemClick}
                htmlFiles={htmlFiles}
            />
        </div>
    );
}
